In [2]:
import pandas as pd
import numpy as np
import pyodbc

In [3]:
luxury=pd.read_csv("Luxury_Housing_Bangalore.csv")

In [4]:
luxury.head(5)

Property_ID       Micro_Market Project_Name Developer_Name  Unit_Size_Sqft  \
0  PROP000001      Sarjapur Road    Project_0            RMZ          4025.0   
1  PROP000002        Indiranagar    Project_1    Puravankara          5760.0   
2  PROP000003  Bannerghatta Road    Project_2   Tata Housing          7707.0   
3  PROP000004       bellary road    Project_3        Embassy          6192.0   
4  PROP000005        Koramangala    Project_4        SNN Raj          7147.0   

  Configuration     Ticket_Price_Cr Transaction_Type Buyer_Type  \
0          4bhk  12.750846039118798          Primary        NRI   
1          3Bhk  16.292151871065954          Primary      Other   
2          4bhk  10.517724412961911          Primary        HNI   
3          3BHK   9.396367494232896          Primary        HNI   
4          4Bhk  15.345392444511946        Secondary        HNI   

  Purchase_Quarter  Connectivity_Score  Amenity_Score   Possession_Status  \
0       2025-03-31            7.990091       5.462863              Launch   
1       2024-06-30            4.839024            NaN  Under construction   
2       2023-12-31            8.131315       8.669227       Ready to move   
3       2024-03-31            7.501657       5.720246       Ready to move   
4       2024-12-31            4.525216       8.609649  Under construction   

  Sales_Channel NRI_Buyer  Locality_Infra_Score  Avg_Traffic_Time_Min  \
0        Broker       yes              9.212491                    18   
1      NRI Desk        no              7.723898                   106   
2        Direct       yes              6.985493                   113   
3        Online       yes              6.100929                   106   
4        Broker        no              5.312510                    18   

              Buyer_Comments  
0       Loved the amenities!  
1                        NaN  
2  Agent was not responsive.  
3        Excellent location!  
4    Too far from my office.

In [5]:
luxury.tail(5)

Property_ID  Micro_Market Project_Name Developer_Name  Unit_Size_Sqft  \
100995  PROP004730  BELLARY ROAD  Project_229        Embassy          8546.0   
100996  PROP059810  Bellary Road  Project_309        Brigade          3408.0   
100997  PROP065099   HENNUR ROAD   Project_98            RMZ          4691.0   
100998  PROP093022   rajajinagar   Project_21        Embassy          7435.0   
100999  PROP023826    whitefield  Project_325     L&T Realty          3218.0   

       Configuration     Ticket_Price_Cr Transaction_Type       Buyer_Type  \
100995         5Bhk+   11.33081004147843        Secondary              CXO   
100996          3bhk  10.829373158307602          Primary              CXO   
100997          4BHK  11.183303152058548          Primary              NRI   
100998          3BHK  10.914156376035923        Secondary            Other   
100999          4bhk           ₹13.27 Cr          Primary  Startup Founder   

       Purchase_Quarter  Connectivity_Score  Amenity_Score  \
100995       2024-12-31            8.552797       6.221131   
100996       2024-09-30            6.879269       9.783611   
100997       2023-12-31            6.753812       8.383013   
100998       2024-06-30            4.437787       5.756247   
100999       2023-12-31            7.760416       9.989290   

         Possession_Status Sales_Channel NRI_Buyer  Locality_Infra_Score  \
100995  Under construction      NRI Desk        no              7.511827   
100996       Ready to move        Direct        no              9.851849   
100997  Under construction        Broker        no              9.101604   
100998  Under construction        Broker       yes              8.588551   
100999  Under construction        Direct       yes              9.917647   

        Avg_Traffic_Time_Min              Buyer_Comments  
100995                    22  Will buy after possession.  
100996                    26   Agent was not responsive.  
100997                    44        Loved the amenities!  
100998                    66         Excellent location!  
100999                    58        Loved the amenities!

In [6]:
luxury.columns

Index(['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name',
       'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr',
       'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter',
       'Connectivity_Score', 'Amenity_Score', 'Possession_Status',
       'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score',
       'Avg_Traffic_Time_Min', 'Buyer_Comments'],
      dtype='object')

In [7]:
luxury['Property_ID'].unique()

array(['PROP000001', 'PROP000002', 'PROP000003', ..., 'PROP099998',
       'PROP099999', 'PROP100000'], dtype=object)

In [8]:
luxury['Micro_Market'].unique()

array(['Sarjapur Road', 'Indiranagar', 'Bannerghatta Road',
       'bellary road', 'Koramangala', 'YELAHANKA', 'whitefield',
       'sarjapur road', 'JP NAGAR', 'Rajajinagar', 'koramangala',
       'WHITEFIELD', 'indiranagar', 'jayanagar', 'Whitefield', 'DOMLUR',
       'yelahanka', 'Mg Road', 'HENNUR ROAD', 'Jayanagar', 'Domlur',
       'Electronic City', 'Hebbal', 'mg road', 'jp nagar',
       'BANNERGHATTA ROAD', 'MG ROAD', 'KANAKAPURA ROAD', 'HEBBAL',
       'BELLARY ROAD', 'electronic city', 'ELECTRONIC CITY',
       'Bellary Road', 'Hennur Road', 'rajajinagar', 'Kanakapura Road',
       'INDIRANAGAR', 'hennur road', 'kanakapura road', 'domlur',
       'bannerghatta road', 'RAJAJINAGAR', 'hebbal', 'Yelahanka',
       'SARJAPUR ROAD', 'KORAMANGALA', 'Jp Nagar', 'JAYANAGAR'],
      dtype=object)

In [9]:
luxury["Micro_Market"] = luxury["Micro_Market"].str.lower().str.title()

In [10]:
luxury['Micro_Market'].unique()

array(['Sarjapur Road', 'Indiranagar', 'Bannerghatta Road',
       'Bellary Road', 'Koramangala', 'Yelahanka', 'Whitefield',
       'Jp Nagar', 'Rajajinagar', 'Jayanagar', 'Domlur', 'Mg Road',
       'Hennur Road', 'Electronic City', 'Hebbal', 'Kanakapura Road'],
      dtype=object)

In [11]:
luxury['Project_Name'].unique()

array(['Project_0', 'Project_1', 'Project_2', 'Project_3', 'Project_4',
       'Project_5', 'Project_6', 'Project_7', 'Project_8', 'Project_9',
       'Project_10', 'Project_11', 'Project_12', 'Project_13',
       'Project_14', 'Project_15', 'Project_16', 'Project_17',
       'Project_18', 'Project_19', 'Project_20', 'Project_21',
       'Project_22', 'Project_23', 'Project_24', 'Project_25',
       'Project_26', 'Project_27', 'Project_28', 'Project_29',
       'Project_30', 'Project_31', 'Project_32', 'Project_33',
       'Project_34', 'Project_35', 'Project_36', 'Project_37',
       'Project_38', 'Project_39', 'Project_40', 'Project_41',
       'Project_42', 'Project_43', 'Project_44', 'Project_45',
       'Project_46', 'Project_47', 'Project_48', 'Project_49',
       'Project_50', 'Project_51', 'Project_52', 'Project_53',
       'Project_54', 'Project_55', 'Project_56', 'Project_57',
       'Project_58', 'Project_59', 'Project_60', 'Project_61',
       'Project_62', 'Project_63', 'P

In [12]:
luxury['Developer_Name'].unique()

array(['RMZ', 'Puravankara', 'Tata Housing', 'Embassy', 'SNN Raj',
       'Brigade', 'Prestige', 'Total Environment', 'Godrej', 'L&T Realty',
       'Sobha'], dtype=object)

In [13]:
luxury['Developer_Name'] = luxury['Developer_Name'].str.replace("&", "", regex=False)

In [14]:
luxury['Unit_Size_Sqft'].unique()

array([4025., 5760., 7707., ..., 3000., 3238., 5432.])

In [15]:
luxury['Unit_Size_Sqft'] = luxury['Unit_Size_Sqft'].astype('float')

In [16]:
luxury['Unit_Size_Sqft'] = luxury['Unit_Size_Sqft'].fillna(luxury['Unit_Size_Sqft'].median()).astype('float')

In [17]:
luxury['Unit_Size_Sqft'].unique()

array([4025., 5760., 7707., ..., 3000., 3238., 5432.])

In [18]:
luxury['Configuration'].unique()

array(['4bhk', '3Bhk', '3BHK', '4Bhk', '5BHK+', '4BHK', '5bhk+', '5Bhk+',
       '3bhk'], dtype=object)

In [19]:
luxury['Configuration'] = luxury['Configuration'].str.upper()

In [20]:
luxury['Configuration'] = luxury['Configuration'].str.replace(" ", "")

In [21]:
luxury['Configuration'] = luxury['Configuration'].str.replace(r"(\d)BHK", r"\1 BHK", regex=True)

In [22]:
luxury['Configuration'] = luxury['Configuration'].str.replace("+", "", regex=False)

In [23]:
luxury['Configuration'].unique()

array(['4 BHK', '3 BHK', '5 BHK'], dtype=object)

In [55]:
luxury['Ticket_Price_Cr'].unique()

array([12.75, 16.29, 10.52, ..., 21.84,  2.89,  1.2 ])

In [25]:
luxury['Ticket_Price_Cr'] = (luxury['Ticket_Price_Cr'].str.replace('₹', '', regex=False).str.replace('Cr', '', regex=False).str.strip())

In [26]:
luxury['Ticket_Price_Cr'] = luxury['Ticket_Price_Cr'].astype(float)

In [27]:
luxury['Ticket_Price_Cr'] = luxury['Ticket_Price_Cr'].fillna(luxury['Ticket_Price_Cr'].median()).astype('float')

In [28]:
luxury['Ticket_Price_Cr'] = luxury['Ticket_Price_Cr'].round(2)

In [29]:
luxury['Transaction_Type'].unique()

array(['Primary', 'Secondary'], dtype=object)

In [30]:
luxury['Buyer_Type'].unique()

array(['NRI', 'Other', 'HNI', 'CXO', 'Startup Founder'], dtype=object)

In [31]:
luxury['Purchase_Quarter'].unique()

array(['2025-03-31', '2024-06-30', '2023-12-31', '2024-03-31',
       '2024-12-31', '2023-09-30', '2024-09-30', '2023-06-30'],
      dtype=object)

In [32]:
luxury['Purchase_Quarter'] = pd.to_datetime(luxury['Purchase_Quarter'])

In [33]:
luxury['Purchase_Quarter'].dtype

dtype('<M8[ns]')

In [34]:
luxury['Connectivity_Score'].unique()

array([7.99009059, 4.83902377, 8.13131488, ..., 6.19334714, 9.43564628,
       5.78629175])

In [35]:
luxury['Connectivity_Score'] = luxury['Connectivity_Score'].fillna(luxury['Connectivity_Score'].median()).astype('float')

In [36]:
luxury['Connectivity_Score'] = luxury['Connectivity_Score'].round(2)

In [37]:
luxury['Amenity_Score'].unique()

array([5.46286299,        nan, 8.66922724, ..., 7.48247301, 6.36927632,
       5.28402643])

In [38]:
luxury['Amenity_Score'] = luxury['Amenity_Score'].round(2)

In [39]:
luxury['Amenity_Score'] = luxury['Amenity_Score'].fillna(luxury['Amenity_Score'].median()).astype('float')

In [40]:
luxury['Possession_Status'].unique()

array(['Launch', 'Under construction', 'Ready to move'], dtype=object)

In [41]:
luxury['Sales_Channel'].unique()

array(['Broker', 'NRI Desk', 'Direct', 'Online'], dtype=object)

In [42]:
luxury['NRI_Buyer'].unique()

array(['yes', 'no'], dtype=object)

In [43]:
luxury['Locality_Infra_Score'].unique()

array([9.21249094, 7.72389833, 6.98549299, ..., 8.98499019, 7.63471681,
       6.03994292])

In [44]:
luxury['Locality_Infra_Score'] = luxury['Locality_Infra_Score'].round(2)

In [45]:
luxury['Avg_Traffic_Time_Min'].unique()

array([ 18, 106, 113,  16,  74,  31,  68, 102,  52,  46,  55,  33,  70,
        77, 118, 116,  58,  32,  51,  56,  43,  65, 105,  27,  34,  95,
        60,  64,  38,  42,  37,  93,  72, 111,  19,  63,  57,  73,  53,
        20,  35, 100, 107,  17,  80,  30,  69,  84,  25, 112,  67,  39,
        50, 114,  47, 101,  23,  66,  78,  71,  44,  85, 104,  40,  99,
        91,  79,  29,  97,  76,  41,  98,  62,  75,  24,  54, 108,  94,
        26,  48,  36,  88, 119,  96, 103,  83, 109,  15,  61,  81,  45,
       117,  92,  87,  82,  21,  59,  22,  86,  49,  90,  28, 115,  89,
       110])

In [46]:
luxury['Buyer_Comments'].unique()

array(['Loved the amenities!', nan, 'Agent was not responsive.',
       'Excellent location!', 'Too far from my office.',
       'Underpriced for location.', 'Will buy after possession.',
       'Great value for money.', 'Connectivity is poor.',
       'Great view from 15th floor.'], dtype=object)

In [47]:
luxury['Buyer_Comments'] = luxury['Buyer_Comments'].astype(str)

In [48]:
luxury['Buyer_Comments'] = luxury['Buyer_Comments'].fillna('Unknown')

In [49]:
luxury.shape

(101000, 18)

In [50]:
luxury.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype         
---  ------                --------------   -----         
 0   Property_ID           101000 non-null  object        
 1   Micro_Market          101000 non-null  object        
 2   Project_Name          101000 non-null  object        
 3   Developer_Name        101000 non-null  object        
 4   Unit_Size_Sqft        101000 non-null  float64       
 5   Configuration         101000 non-null  object        
 6   Ticket_Price_Cr       101000 non-null  float64       
 7   Transaction_Type      101000 non-null  object        
 8   Buyer_Type            101000 non-null  object        
 9   Purchase_Quarter      101000 non-null  datetime64[ns]
 10  Connectivity_Score    101000 non-null  float64       
 11  Amenity_Score         101000 non-null  float64       
 12  Possession_Status     101000 non-null  object        
 13 

In [51]:
luxury.describe()

Unit_Size_Sqft  Ticket_Price_Cr               Purchase_Quarter  \
count   101000.000000    101000.000000                         101000   
mean      5974.037812        12.651030  2024-05-15 06:47:26.922772224   
min         -1.000000        -1.420000            2023-06-30 00:00:00   
25%       4648.000000        10.260000            2023-09-30 00:00:00   
50%       5990.000000        12.040000            2024-03-31 00:00:00   
75%       7332.000000        13.830000            2024-09-30 00:00:00   
max       8999.000000       100.000000            2025-03-31 00:00:00   
std       1692.389594         7.278481                            NaN   

       Connectivity_Score  Amenity_Score  Locality_Infra_Score  \
count       101000.000000  101000.000000         101000.000000   
mean             6.992602       7.503302              7.498424   
min              4.000000       5.000000              5.000000   
25%              5.490000       6.400000              6.250000   
50%              6.990000       7.500000              7.500000   
75%              8.490000       8.620000              8.750000   
max             10.000000      10.000000             10.000000   
std              1.731793       1.366901              1.443126   

       Avg_Traffic_Time_Min  
count         101000.000000  
mean              67.182921  
min               15.000000  
25%               41.000000  
50%               67.000000  
75%               93.000000  
max              119.000000  
std               30.271611

In [52]:
luxury.isnull().sum()

Property_ID             0
Micro_Market            0
Project_Name            0
Developer_Name          0
Unit_Size_Sqft          0
Configuration           0
Ticket_Price_Cr         0
Transaction_Type        0
Buyer_Type              0
Purchase_Quarter        0
Connectivity_Score      0
Amenity_Score           0
Possession_Status       0
Sales_Channel           0
NRI_Buyer               0
Locality_Infra_Score    0
Avg_Traffic_Time_Min    0
Buyer_Comments          0
dtype: int64

In [53]:
luxury['Buyer_Comments'].str.isnumeric().sum

<bound method Series.sum of 0         False
1         False
2         False
3         False
4         False
          ...  
100995    False
100996    False
100997    False
100998    False
100999    False
Name: Buyer_Comments, Length: 101000, dtype: bool>

In [54]:
data_copy=luxury.copy()

In [59]:
conn = pyodbc.connect(
    "Driver={SQL Server};"
    "Server=LAPTOP-8H7M1112\SQLEXPRESS;"  
    "Database=luxury_sale;"
    "Trusted_Connection=yes;"
)

cursor = conn.cursor()

query="""IF NOT EXISTS (SELECT * FROM sys.objects WHERE name='luxury')
BEGIN
    create table luxury(
       Property_ID nvarchar(25),
       Micro_Market varchar(255),
       Project_Name nvarchar(255),
       Developer_Name nvarchar(255),
       Unit_Size_Sqft float(50),
       Configuration nvarchar(50),
       Ticket_Price_Cr float(50),
       Transaction_Type nvarchar(255),
       Buyer_Type varchar(255),
       Purchase_Quarter date,
       Connectivity_Score float(50),
       Amenity_Score float(50),
       Possession_Status varchar(255),
       Sales_Channel varchar(100),
       NRI_Buyer varchar(100),
       Locality_Infra_Score float(50),
       Avg_Traffic_Time_Min nvarchar(50),
       Buyer_Comments nvarchar(100)
    )
end
"""
cursor.execute(query)
conn.commit()

queries = """
INSERT INTO luxury
(Property_ID, Micro_Market, Project_Name, Developer_Name,
       Unit_Size_Sqft, Configuration, Ticket_Price_Cr,
       Transaction_Type, Buyer_Type, Purchase_Quarter,
       Connectivity_Score, Amenity_Score, Possession_Status,
       Sales_Channel, NRI_Buyer, Locality_Infra_Score,
       Avg_Traffic_Time_Min, Buyer_Comments)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
"""

data=luxury.values.tolist()
cursor.executemany(queries, data )
conn.commit()
